"""Recruiting records — job postings and candidate data for the recruiting assistant.

Backing data for the data-access layer in data_service.py.
"""

JOB_POSTINGS = {'JOB-10001': {'job_id': 'JOB-10001',
               'title': 'Senior Backend Engineer',
               'department': 'Engineering',
               'location': 'San Francisco, CA',
               'employment_type': 'Full-time',
               'seniority': 'Senior',
               'salary_range': {'min': 165000, 'max': 210000, 'currency': 'USD'},
               'required_skills': ['Python',
                                   'Go',
                                   'Kubernetes',
                                   'PostgreSQL',
                                   'AWS',
                                   'distributed systems'],
               'min_years_experience': 5,
               'description': 'Design, build, and operate backend systems at scale.',
               'posted_date': '2026-05-01',
               'recruiter_contact': 'Ava Mills',
               'status': 'open'},
 'JOB-10002': {'job_id': 'JOB-10002',
               'title': 'Data Scientist',
               'department': 'Data & Analytics',
               'location': 'Remote (US)',
               'employment_type': 'Full-time',
               'seniority': 'Mid',
               'salary_range': {'min': 140000, 'max': 175000, 'currency': 'USD'},
               'required_skills': ['Python', 'SQL', 'Spark', 'data modeling'],
               'min_years_experience': 3,
               'description': 'Build models and analyses that drive product decisions.',
               'posted_date': '2026-05-12',
               'recruiter_contact': 'Daniel Weiss',
               'status': 'open'},
 'JOB-10003': {'job_id': 'JOB-10003',
               'title': 'Frontend Engineer',
               'department': 'Engineering',
               'location': 'New York, NY',
               'employment_type': 'Full-time',
               'seniority': 'Mid',
               'salary_range': {'min': 130000, 'max': 165000, 'currency': 'USD'},
               'required_skills': ['TypeScript', 'React', 'GraphQL', 'CI/CD'],
               'min_years_experience': 3,
               'description': 'Build accessible, high-performance web interfaces.',
               'posted_date': '2026-05-03',
               'recruiter_contact': 'Jin Chen',
               'status': 'open'},
 'JOB-10004': {'job_id': 'JOB-10004',
               'title': 'DevOps Engineer',
               'department': 'Infrastructure',
               'location': 'Austin, TX',
               'employment_type': 'Full-time',
               'seniority': 'Senior',
               'salary_range': {'min': 150000, 'max': 190000, 'currency': 'USD'},
               'required_skills': ['Terraform', 'AWS', 'Kubernetes', 'CI/CD'],
               'min_years_experience': 5,
               'description': 'Own CI/CD and cloud infrastructure for the platform.',
               'posted_date': '2026-04-28',
               'recruiter_contact': 'Kavya Patel',
               'status': 'open'},
 'JOB-10005': {'job_id': 'JOB-10005',
               'title': 'Machine Learning Engineer',
               'department': 'Machine Learning',
               'location': 'Seattle, WA',
               'employment_type': 'Full-time',
               'seniority': 'Senior',
               'salary_range': {'min': 170000, 'max': 215000, 'currency': 'USD'},
               'required_skills': ['Python', 'PyTorch', 'Spark', 'distributed systems'],
               'min_years_experience': 5,
               'description': 'Train and serve ML models in production.',
               'posted_date': '2026-05-09',
               'recruiter_contact': 'Linh Nguyen',
               'status': 'open'},
 'JOB-10006': {'job_id': 'JOB-10006',
               'title': 'Site Reliability Engineer',
               'department': 'Infrastructure',
               'location': 'Remote (US)',
               'employment_type': 'Full-time',
               'seniority': 'Senior',
               'salary_range': {'min': 160000, 'max': 200000, 'currency': 'USD'},
               'required_skills': ['Go', 'Kubernetes', 'Redis', 'CI/CD'],
               'min_years_experience': 5,
               'description': 'Keep production reliable; own SLOs and on-call.',
               'posted_date': '2026-05-18',
               'recruiter_contact': 'Marco Rossi',
               'status': 'open'},
 'JOB-10007': {'job_id': 'JOB-10007',
               'title': 'Security Engineer',
               'department': 'Security',
               'location': 'Denver, CO',
               'employment_type': 'Full-time',
               'seniority': 'Senior',
               'salary_range': {'min': 160000, 'max': 205000, 'currency': 'USD'},
               'required_skills': ['Python', 'AWS', 'gRPC', 'distributed systems'],
               'min_years_experience': 6,
               'description': 'Harden services and lead threat modeling.',
               'posted_date': '2026-05-20',
               'recruiter_contact': 'Ola Adeyemi',
               'status': 'open'},
 'JOB-10008': {'job_id': 'JOB-10008',
               'title': 'Full Stack Developer',
               'department': 'Engineering',
               'location': 'Chicago, IL',
               'employment_type': 'Full-time',
               'seniority': 'Mid',
               'salary_range': {'min': 135000, 'max': 170000, 'currency': 'USD'},
               'required_skills': ['TypeScript', 'React', 'Python', 'PostgreSQL', 'REST APIs'],
               'min_years_experience': 4,
               'description': 'Ship end-to-end features across the web stack.',
               'posted_date': '2026-05-15',
               'recruiter_contact': 'Sara Brown',
               'status': 'open'},
 'JOB-10009': {'job_id': 'JOB-10009',
               'title': 'Staff Software Engineer',
               'department': 'Platform',
               'location': 'San Francisco, CA',
               'employment_type': 'Full-time',
               'seniority': 'Staff',
               'salary_range': {'min': 180000, 'max': 240000, 'currency': 'USD'},
               'required_skills': ['Python', 'Go', 'distributed systems', 'Kubernetes', 'PostgreSQL'],
               'min_years_experience': 8,
               'description': 'Set technical direction for core platform services.',
               'posted_date': '2026-04-10',
               'recruiter_contact': 'Tara Kim',
               'status': 'open'},
 'JOB-10010': {'job_id': 'JOB-10010',
               'title': 'Engineering Manager',
               'department': 'Engineering',
               'location': 'Boston, MA',
               'employment_type': 'Full-time',
               'seniority': 'Staff',
               'salary_range': {'min': 190000, 'max': 250000, 'currency': 'USD'},
               'required_skills': ['people management', 'distributed systems', 'AWS', 'Python'],
               'min_years_experience': 8,
               'description': 'Lead and grow a team building backend platform services.',
               'posted_date': '2026-04-22',
               'recruiter_contact': 'Rosa Garcia',
               'status': 'open'}}

CANDIDATES = {'CAND-12853': {'name': 'Omar Okafor',
                'email': 'omar.okafor@example.com',
                'rejected': False,
                'work_history': [{'company': 'Lakeside Analytics',
                                  'title': 'Frontend Engineer',
                                  'start_date': '2024-01',
                                  'end_date': 'Present'},
                                 {'company': 'Arcadia Data',
                                  'title': 'Frontend Engineer',
                                  'start_date': '2020-09',
                                  'end_date': '2024-01'}],
                'education': [{'institution': 'University of Illinois',
                               'degree': 'M.S.',
                               'field': 'Computer Science',
                               'graduation_year': 2008}],
                'skills': ['TypeScript',
                           'React',
                           'GraphQL',
                           'CI/CD',
                           'distributed systems'],
                'years_experience': 9},
 'CAND-15229': {'name': 'Yuki Nguyen',
                'email': 'yuki.nguyen@example.com',
                'rejected': False,
                'work_history': [{'company': 'Ironwood Compute',
                                  'title': 'Machine Learning Engineer',
                                  'start_date': '2024-06',
                                  'end_date': 'Present'},
                                 {'company': 'Lakeside Analytics',
                                  'title': 'Data Scientist',
                                  'start_date': '2020-04',
                                  'end_date': '2024-03'}],
                'education': [{'institution': 'University of Washington',
                               'degree': 'M.S.',
                               'field': 'Data Science',
                               'graduation_year': 2010}],
                'skills': ['Python', 'PyTorch', 'Spark', 'distributed systems', 'PostgreSQL'],
                'years_experience': 10},
 'CAND-18993': {'name': 'Sven Smith',
                'email': 'sven.smith@example.com',
                'rejected': False,
                'work_history': [{'company': 'Cedar Peak Software',
                                  'title': 'Senior Backend Engineer',
                                  'start_date': '2024-10',
                                  'end_date': 'Present'},
                                 {'company': 'Cedar Peak Software',
                                  'title': 'Backend Engineer',
                                  'start_date': '2022-08',
                                  'end_date': '2024-11'}],
                'education': [{'institution': 'University of Michigan',
                               'degree': 'M.S.',
                               'field': 'Computer Science',
                               'graduation_year': 2011}],
                'skills': ['Python',
                           'Go',
                           'Kubernetes',
                           'PostgreSQL',
                           'AWS',
                           'distributed systems'],
                'years_experience': 7},
 'CAND-26912': {'name': 'Elena Santos',
                'email': 'elena.santos@example.com',
                'rejected': False,
                'work_history': [{'company': 'Stonebridge Systems',
                                  'title': 'Security Engineer',
                                  'start_date': '2025-05',
                                  'end_date': 'Present'},
                                 {'company': 'Northgate Solutions',
                                  'title': 'Security Engineer',
                                  'start_date': '2023-12',
                                  'end_date': '2025-04'}],
                'education': [{'institution': 'Cornell University',
                               'degree': 'Ph.D.',
                               'field': 'Computer Science',
                               'graduation_year': 2022}],
                'skills': ['Python', 'AWS', 'gRPC', 'distributed systems', 'Docker'],
                'years_experience': 7},
 'CAND-39002': {'name': 'Chloe Rodriguez',
                'email': 'chloe.rodriguez@example.com',
                'rejected': False,
                'work_history': [{'company': 'Stonebridge Systems',
                                  'title': 'Site Reliability Engineer',
                                  'start_date': '2023-05',
                                  'end_date': 'Present'},
                                 {'company': 'Cedar Peak Software',
                                  'title': 'DevOps Engineer',
                                  'start_date': '2021-04',
                                  'end_date': '2023-07'}],
                'education': [{'institution': 'University of Illinois',
                               'degree': 'M.S.',
                               'field': 'Data Science',
                               'graduation_year': 2016}],
                'skills': ['Go', 'Kubernetes', 'Redis', 'CI/CD', 'AWS'],
                'years_experience': 5},
 'CAND-70001': {'name': 'Maria Garcia',
                'email': 'maria.garcia@example.com',
                'rejected': False,
                'work_history': [{'company': 'Brightline Analytics',
                                  'title': 'Senior Backend Engineer',
                                  'start_date': '2019-01',
                                  'end_date': 'Present'},
                                 {'company': 'Meridian Systems',
                                  'title': 'Backend Engineer',
                                  'start_date': '2016-01',
                                  'end_date': '2019-01'}],
                'education': [{'institution': 'UC Berkeley',
                               'degree': 'M.S.',
                               'field': 'Computer Science',
                               'graduation_year': 2014}],
                'skills': ['Python',
                           'Go',
                           'Kubernetes',
                           'PostgreSQL',
                           'AWS',
                           'Docker',
                           'REST APIs'],
                'years_experience': 10},
 'CAND-71001': {'name': 'Noah Williams',
                'email': 'noah.williams@example.com',
                'rejected': False,
                'work_history': [{'company': 'Lakeside Analytics',
                                  'title': 'Data Scientist',
                                  'start_date': '2020-01',
                                  'end_date': 'Present'},
                                 {'company': 'Cedar Peak Software',
                                  'title': 'Data Analyst',
                                  'start_date': '2018-06',
                                  'end_date': '2020-01'}],
                'education': [{'institution': 'University of Washington',
                               'degree': 'M.S.',
                               'field': 'Data Science',
                               'graduation_year': 2019}],
                'skills': ['Python', 'SQL', 'Spark', 'data modeling', 'PyTorch', 'REST APIs'],
                'years_experience': 6},
 'CAND-90001': {'name': 'Hannah Becker',
                'email': 'hannah.becker@example.com',
                'rejected': False,
                'work_history': [{'company': 'Summit Ridge Labs',
                                  'title': 'Senior Backend Engineer',
                                  'start_date': '2021-03',
                                  'end_date': 'Present'},
                                 {'company': 'Greenfield Networks',
                                  'title': 'Backend Engineer',
                                  'start_date': '2017-08',
                                  'end_date': '2021-02'}],
                'education': [{'institution': 'Georgia Tech',
                               'degree': 'B.S.',
                               'field': 'Computer Science',
                               'graduation_year': 2016}],
                'skills': ['Python',
                           'Go',
                           'Kubernetes',
                           'PostgreSQL',
                           'AWS',
                           'distributed systems'],
                'years_experience': 8},
 'CAND-90002': {'name': 'Tomás Herrera',
                'email': 'tomas.herrera@example.com',
                'rejected': False,
                'work_history': [{'company': 'Ironwood Compute',
                                  'title': 'Machine Learning Engineer',
                                  'start_date': '2022-09',
                                  'end_date': 'Present'},
                                 {'company': 'Arcadia Data',
                                  'title': 'Data Scientist',
                                  'start_date': '2019-05',
                                  'end_date': '2022-08'}],
                'education': [{'institution': 'Cornell University',
                               'degree': 'M.S.',
                               'field': 'Statistics',
                               'graduation_year': 2018}],
                'skills': ['Python', 'PyTorch', 'Spark', 'distributed systems', 'SQL'],
                'years_experience': 7},
 'CAND-90003': {'name': 'Grace Adeyemi',
                'email': 'grace.adeyemi@example.com',
                'rejected': False,
                'work_history': [{'company': 'Fairview Labs',
                                  'title': 'DevOps Engineer',
                                  'start_date': '2023-02',
                                  'end_date': 'Present'},
                                 {'company': 'Westwind Cloud',
                                  'title': 'Platform Engineer',
                                  'start_date': '2019-11',
                                  'end_date': '2023-01'}],
                'education': [{'institution': 'University of Texas at Austin',
                               'degree': 'B.S.',
                               'field': 'Electrical Engineering',
                               'graduation_year': 2017}],
                'skills': ['Terraform', 'AWS', 'Kubernetes', 'CI/CD', 'Docker'],
                'years_experience': 6},
 'CAND-50001': {'name': 'Priya Nair',
                'email': 'priya.nair@example.com',
                'rejected': True,
                'work_history': [{'company': 'Brightwave Apps',
                                  'title': 'Frontend Engineer',
                                  'start_date': '2022-03',
                                  'end_date': 'Present'},
                                 {'company': 'Cedar Peak Software',
                                  'title': 'Frontend Engineer',
                                  'start_date': '2019-07',
                                  'end_date': '2022-02'}],
                'education': [{'institution': 'University of Illinois',
                               'degree': 'B.S.',
                               'field': 'Computer Science',
                               'graduation_year': 2019}],
                'skills': ['TypeScript', 'React', 'GraphQL', 'CI/CD'],
                'years_experience': 4},
 'CAND-50002': {'name': "Liam O'Brien",
                'email': 'liam.obrien@example.com',
                'rejected': True,
                'work_history': [{'company': 'Meridian Systems',
                                  'title': 'Backend Engineer',
                                  'start_date': '2020-02',
                                  'end_date': 'Present'},
                                 {'company': 'Greenfield Networks',
                                  'title': 'Software Engineer',
                                  'start_date': '2017-06',
                                  'end_date': '2020-01'}],
                'education': [{'institution': 'University of Michigan',
                               'degree': 'B.S.',
                               'field': 'Computer Science',
                               'graduation_year': 2017}],
                'skills': ['Python', 'Go', 'PostgreSQL', 'AWS', 'Docker'],
                'years_experience': 6},
 'CAND-50003': {'name': 'Sofia Rossi',
                'email': 'sofia.rossi@example.com',
                'rejected': True,
                'work_history': [{'company': 'Lakeside Analytics',
                                  'title': 'Data Scientist',
                                  'start_date': '2021-08',
                                  'end_date': 'Present'},
                                 {'company': 'Arcadia Data',
                                  'title': 'Data Analyst',
                                  'start_date': '2018-09',
                                  'end_date': '2021-07'}],
                'education': [{'institution': 'University of Washington',
                               'degree': 'M.S.',
                               'field': 'Statistics',
                               'graduation_year': 2018}],
                'skills': ['Python', 'SQL', 'Spark', 'data modeling'],
                'years_experience': 5},
 'CAND-50004': {'name': 'Aiden Park',
                'email': 'aiden.park@example.com',
                'rejected': True,
                'work_history': [{'company': 'Westwind Cloud',
                                  'title': 'DevOps Engineer',
                                  'start_date': '2020-05',
                                  'end_date': 'Present'},
                                 {'company': 'Fairview Labs',
                                  'title': 'Systems Engineer',
                                  'start_date': '2017-03',
                                  'end_date': '2020-04'}],
                'education': [{'institution': 'Georgia Tech',
                               'degree': 'B.S.',
                               'field': 'Computer Engineering',
                               'graduation_year': 2016}],
                'skills': ['Terraform', 'AWS', 'Kubernetes', 'CI/CD'],
                'years_experience': 7},
 'CAND-50005': {'name': 'Mei Lin',
                'email': 'mei.lin@example.com',
                'rejected': True,
                'work_history': [{'company': 'Ironwood Compute',
                                  'title': 'Machine Learning Engineer',
                                  'start_date': '2021-01',
                                  'end_date': 'Present'},
                                 {'company': 'Brightline Analytics',
                                  'title': 'Data Scientist',
                                  'start_date': '2018-04',
                                  'end_date': '2020-12'}],
                'education': [{'institution': 'Cornell University',
                               'degree': 'M.S.',
                               'field': 'Computer Science',
                               'graduation_year': 2018}],
                'skills': ['Python', 'PyTorch', 'Spark', 'distributed systems'],
                'years_experience': 6}}

RECRUITER_IDS = [{'recruiter_id': 'recruiter_amills',
  'name': 'Ava Mills',
  'email': 'ava.mills@northpoint.com'},
 {'recruiter_id': 'recruiter_dweiss',
  'name': 'Daniel Weiss',
  'email': 'daniel.weiss@northpoint.com'},
 {'recruiter_id': 'recruiter_jchen',
  'name': 'Jin Chen',
  'email': 'jin.chen@northpoint.com'},
 {'recruiter_id': 'recruiter_kpatel',
  'name': 'Kavya Patel',
  'email': 'kavya.patel@northpoint.com'},
 {'recruiter_id': 'recruiter_lnguyen',
  'name': 'Linh Nguyen',
  'email': 'linh.nguyen@northpoint.com'},
 {'recruiter_id': 'recruiter_mrossi',
  'name': 'Marco Rossi',
  'email': 'marco.rossi@northpoint.com'},
 {'recruiter_id': 'recruiter_oadeyemi',
  'name': 'Ola Adeyemi',
  'email': 'ola.adeyemi@northpoint.com'},
 {'recruiter_id': 'recruiter_sbrown',
  'name': 'Sara Brown',
  'email': 'sara.brown@northpoint.com'},
 {'recruiter_id': 'recruiter_tkim',
  'name': 'Tara Kim',
  'email': 'tara.kim@northpoint.com'},
 {'recruiter_id': 'recruiter_rgarcia',
  'name': 'Rosa Garcia',
  'email': 'rosa.garcia@northpoint.com'}]
